import localFont from "next/font/local";
import { twMerge } from "tailwind-merge";
import "./globals.css";

const aileron = localFont({
  src: [
    { path: "./fonts/Aileron-Regular.woff2", weight: "400", style: "normal" },
    { path: "./fonts/Aileron-Bold.woff2", weight: "700", style: "normal" },
  ],
  variable: "--font-aileron",
  display: "swap",
});

const swearDisplay = localFont({
  src: [{ path: "./fonts/SwearDisplay.otf", weight: "300", style: "normal" }],
  variable: "--font-swear",
  display: "swap",
});

const swearDisplayItalic = localFont({
  src: [
    { path: "./fonts/SwearDisplay-Italic.otf", weight: "300", style: "italic" },
  ],
  variable: "--font-swear-italic",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="es"
      className={twMerge(
        aileron.variable,
        swearDisplay.variable,
        swearDisplayItalic.variable
      )}
    >
      <body className={twMerge(aileron.className, "text-[#262111] antialiased")}>
        {children}
      </body>
    </html>
  );
}
